@Task_tracker.API_HostAddress = http://localhost:5270

POST {{Task_tracker.API_HostAddress}}/account/register/
Content-Type: application/json
{
  "UserName": "Wrrre",
  "Email": "dsafsa@gmail.com",
  "Password": "passw"
}
###

POST {{Task_tracker.API_HostAddress}}/account/login/
Content-Type: application/json
{
  "UserName": "Wrrre",
  "Email": "dsafsa@gmail.com",
  "Password": "passw"
}
###